### ISSUE TITLE
[PE-D][Tester C] Wrong error message when trying to edit an entry that is not in the list

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-W14-3/tp#155]
Hi, so far your edit command is working according to the UG! Unfortunately, the error message when I try to edit an entry that is not in the list does not match the error.

In my example, I have exactly 10 people in my list. When I run `edit 104`, this happens:

![image.png](https://raw.githubusercontent.com/oeggy03/ped/main/files/ae0045d5-171c-4f1d-a3c7-d15518abd09f.png)

As you can see, the most pressing issue here should be the index being out of bounds, so I think maybe you can change your error message to reflect that.

When I do specify the parameters after and run `edit 104 n\Johnny`:

![image.png](https://raw.githubusercontent.com/oeggy03/ped/main/files/728ce226-220d-48a5-80e7-ce2937c4af1d.png)

The error message is correct.

So I believe that this is very likely a small error of the parameters being checked first, before the index.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: oeggy03/ped#1

**Comment by Cloud7050** [comment]
Could consider changing the order of error checking if feasible. As long as the feature freeze allows.

**Comment by Cloud7050** [comment]
This arises because the parser first checks that the format is valid - ie we need enough params specified. Only later, during attempted execution, does the partially validated non-negative unsigned integer get checked against the list of all contacts, to see if the index actually exists. Thus the depicted error is the one that the user encounters first.

**Comment by Cloud7050** [comment]
**Decision**

Subsumed by #152.

The planned enhancement in the aforementioned issue would also fix this problem, by way of showing all problems with the command instead of just the first one.

**Comment by Cloud7050** [comment]
We ended up closing #152 for other reasons. So looking at this again, perhaps this change is a bit subjective (wrt which error is more pressing).

Given the explanation above about how the command is first parsed, it will not be that easy to implement, since a meaningful command doesn't get parsed at all.

Overall, low priority, and since we have hit the max 8 planned enhancements, we will not be writing about this.
